### ISSUE TITLE
TypeError: formData.getBoundary is not a function

### ISSUE THREAD

**Issue by GirkovArpa** [mistval/node-fetch-cache#15]
```
file:///_/node_modules/node-fetch-cache/src/index.js:20
  const boundary = formData.getBoundary();
                            ^

TypeError: formData.getBoundary is not a function
    at getFormDataCacheKey (file:///_/node_modules/node-fetch-cache/src/index.js:20:29)
    at getBodyCacheKeyJson (file:///_/node_modules/node-fetch-cache/src/index.js:49:12)
    at getCacheKey (file:///_/node_modules/node-fetch-cache/src/index.js:84:27)
    at getResponse (file:///_/node_modules/node-fetch-cache/src/index.js:92:20)
    at fetchCache (file:///_/node_modules/node-fetch-cache/src/index.js:139:35)
    at async main (file:///_/index.js:19:33)
```

**Comment by GirkovArpa** [comment]
I was importing `FormData` from the package `formdata-node`.

Changing to `form-data` solved this.
